# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- develop

pool:
  vmImage: 'ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.14.2'
  displayName: 'Install Node.js'

- script: |
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4
    echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.0.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
    sudo service mongod start
  displayName: 'install mongodb'

- script: |
    npm install -g yarn
  displayName: 'install yarn'

- script: |
    yarn install
  displayName: 'install project dependencies'

- script: |
    yarn build
  displayName: 'build project'

# - script: |
#     yarn test
#   displayName: 'run all tests'
